### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by espanista** [HACK3RY2J/Anon-SMS#17]
Traceback (most recent call last):
  File "/root/Anon-SMS/send.py", line 159, in <module>
    print(resp.json())
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mdimdr** [comment]
thats not send sms to +98 country code

**Comment by HACK3RY2J** [comment]
Kindly send the output error message

**Comment by sameerapr** [comment]
Error![Screenshot_20211005_230003_com.termux.jpg](https://user-images.githubusercontent.com/51504402/136073381-c4814bd2-5480-49d9-b190-ffe4176e9e4f.jpg)
