### ISSUE TITLE
If i try to send i see this Error ?

### ISSUE THREAD

**Issue by haszimoto** [HACK3RY2J/Anon-SMS#31]
Traceback (most recent call last):
  File "/home/user/Anon-SMS/Anon-SMS/send.py", line 159, in <module>
    print(resp.json())
  File "/home/user/.local/lib/python3.9/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by HACK3RY2J** [comment]
Try updating python
